version: '3'
services:
  dbPostgresql:
      image: postgres:latest
      ports:
          - "5400:5432"
      networks:
          - overlay
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: "prueba_tecnica_polimundo"
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
          
volumes:
  postgres-data:

networks:
  overlay:
