version: '3'
services:
  db:
      image: postgres:latest
      ports:
          - "5400:5432"
      networks:
          - overlay
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: "prueba_tecnica_polimundo"
          
volumes:
  postgres-data:

networks:
  overlay:
